[build]
rustflags = [
    "-C", "target-cpu=znver3"
]

[target.'cfg(target_os = "windows")']
rustflags = [
"--cfg", "windows_slim_errors"
]
[target.'cfg(target_os = "linux")']
rustflags = [
]

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 's'
panic = "abort"
strip = true
